config/routes.rb
Rails.application.routes.draw do
  resources :games, only: %i[create show]
  resources :chats, only: %i[index show] do
    resources :messages, only: %i[new create]
  end

  root 'pages#home'
  get 'clicker', to: 'pages#clicker'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :creator, class_name: 'User'

  has_many :messages

  def opponent_of(me)
    me == user ? creator : user
  end

  def last_message
    messages.order(created_at: :desc).first
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  
end

app/models/game.rb
class Game < ApplicationRecord
  include GamesHelper

  SIGNS = ['X', 'O'].freeze

  WIN_STATES = [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [0, 3, 6],
    [1, 4, 7],
    [2, 5, 8],
    [0, 4, 8],
    [2, 4, 6]
  ].freeze

  belongs_to :playerX, class_name: 'User'
  belongs_to :playerO, class_name: 'User'

  def opponent_of(me)
    me == playerX ? playerO : playerX
  end

  def sign_of(user)
    user == playerX ? 'X' : 'O'
  end

  def start
    puts SIGNS.sample
    self.update(turn_status: SIGNS.sample)
    self.broadcast_game_status()
  end

  def broadcast_game_status()
    cable_ready[DeskChannel].inner_html(
      selector: "#status",
      html: self.decorided_status()
    ).broadcast_to(self)
  end

  def decorided_status
    case self.turn_status
    when 'X', 'O'
      then "Player <span class='display-player player#{self.turn_status}'>#{self.turn_status}</span> turn"
    when 'X won'
      then "Player <span class='display-player playerX'>X</span> won"
    when 'O won'
      then "Player <span class='display-player playerO'>O</span> won"
    end
  end

  def opposite_sign(sign)
    sign == 'X' ? 'O' : 'X'
  end

  def check_win_state
    game_state = self.state

    WIN_STATES.each do |win_state|
      if game_state[win_state[0]] == game_state[win_state[1]] && game_state[win_state[0]] == game_state[win_state[2]] && game_state[win_state[0]] != ''
        return "#{game_state[win_state[0]]} won"
      end
    end

    return
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :sender, class_name: 'User', inverse_of: :sended_invitations
  belongs_to :receiver, class_name: 'User', inverse_of: :received_invitations

  validates :sender_id, uniqueness: {
    scope: :receiver_id,
    message: 'Invitation already sended'
  }

  # validates :receiver_id, uniqueness: {
  #   scope: :sender_id,
  #   message: 'Invitation already sended'
  # }

  def accept
    update!(confirmed: true)
    sender.friends << receiver
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  after_create_commit -> {
    broadcast_update_to "chat_#{self.chat.id}_#{self.chat.user.id}",
      partial: "chats/chat_item",
      locals: { chat: self.chat, user: self.chat.user },
      target: 'chat'

    broadcast_update_to "chat_#{self.chat.id}_#{self.chat.creator.id}",
      partial: "chats/chat_item",
      locals: { chat: self.chat, user: self.chat.creator },
      target: 'chat'
  }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :authentication_keys => [:username]

  has_and_belongs_to_many :friends,
    class_name: 'User',
    join_table: 'friendships',
    association_foreign_key: 'friend_id',
    after_add: :create_complement_friendship,
    after_remove: :remove_complement_friendship

  has_many :received_invitations, class_name: 'Invitation', foreign_key: 'receiver_id', inverse_of: :receiver
  has_many :sended_invitations, class_name: 'Invitation', foreign_key: 'sender_id', inverse_of: :sender

  has_many :created_chats, class_name: 'Chat', foreign_key: 'creator_id', inverse_of: :creator
  has_many :involved_chats, class_name: 'Chat', foreign_key: 'user_id', inverse_of: :user

  has_many :x_games, class_name: 'Game', foreign_key: 'playerX_id', inverse_of: :playerX
  has_many :o_games, class_name: 'Game', foreign_key: 'playerO_id', inverse_of: :playerO

  validates :username, uniqueness: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.username = auth.info.username
    user.password = Devise.friendly_token[0,20]
    end
  end

  def send_invitation_to(user)
    Invitation.create!(sender: self, receiver: user)
  end

  def chats
    created_chats + involved_chats
  end

  def pending_games
    x_games + o_games
  end

  def chat_with(friend)
    created_chats.where(user: friend).first || involved_chats.where(creator: friend).first
  end

  private

  def create_complement_friendship(friend)
    friend.friends << self  unless friend.friends.include?(self)
  end

  def remove_complement_friendship(friend)
    friend.friends.delete(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :fetch_chat
  before_action :authenticate_user!

  def index
    @current_page = 'Chats'
    @friends = current_user.friends
  end

  def show
  end

  private

  def fetch_chat
    @chat = Chat.find_by(id: params[:id])
  end

  def authenticate
    raise ActionController::RoutingError.new('Not Found') unless member?
  end

  def member?
    current_user == @chat.user || current_user == @chat.creator
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @game = Game.find_by(id: params[:id])
    @render_widgets = true
    session[:current_game_id] = @game.id
  end

  def create
    Game.create!(playerX_id: params[:user_id], playerO_id: params[:friend_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def new
    feach_chat
    @message = Message.new
  end

  def create
    feach_chat
    Message.create!(user: current_user, chat: @chat, content: params[:message][:content])
    redirect_to "/chats/#{@chat.id}/messages/new"
  end

  private

  def feach_chat
    @chat = Chat.find_by(id: params[:chat_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def home
    session[:current_user_id] = current_user.id
    @current_page = 'Home'
    @chats = current_user.chats
  end

  def clicker
    @count = session[:count].to_i
    @current_page = 'Clicker'
  end
end

app/helpers/appearance_helper.rb
module AppearanceHelper
  include CableReady::Broadcaster

  def user_appear(id)
    REDIS.sadd('online', id)
  end

  def user_disappear(id)
    REDIS.srem('online', id)
  end

  def online_count
    REDIS.smembers('online').count
  end

  def broadcast_counter
    cable_ready["appearance"].inner_html(
      selector: '#appearance',
      html: online_count.to_s
    )
    cable_ready.broadcast
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/games_helper.rb
module GamesHelper
  include CableReady::Broadcaster

  def broadcast_game_status(game)
    cable_ready[DeskChannel].inner_html(
      selector: "#status",
      html: "Player <span class='display-player player#{game.turn_status}'>#{game.turn_status}</span> turn"
    ).broadcast_to(game)
  end

  def opposite_sign(sign)
    sign == 'X' ? 'O' : 'X'
  end
end

app/views/chats/_chat_item.html.erb
<%= turbo_stream_from "chat_#{chat.id}_#{user.id}" %>
<div class="chat">
    <div class="chat-header clearfix">
        <div class="row">
            <div class="col-lg-6">
                <a href="javascript:void(0);" data-toggle="modal" data-target="#view_info">
                    <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="avatar">
                </a>
                <div class="chat-about">
                    <h6 class="m-b-0"><%= chat.opponent_of(user).username %></h6>
                    <small>Last seen: 2 hours ago</small>
                </div>
            </div>
            <div class="col-lg-6 hidden-sm text-right">
                <a href="javascript:void(0);" class="btn btn-outline-secondary"><i class="fa fa-camera"></i></a>
                <a href="javascript:void(0);" class="btn btn-outline-primary"><i class="fa fa-image"></i></a>
                <a href="javascript:void(0);" class="btn btn-outline-info"><i class="fa fa-cogs"></i></a>
                <a href="javascript:void(0);" class="btn btn-outline-warning"><i class="fa fa-question"></i></a>
            </div>
        </div>
    </div>
    <div class="chat-history" style='height: 50vh; overflow: scroll'>
      <ul class="m-b-0" data-controller='scroll'>
        <% chat.messages.each do |message| %>
          <%= render 'chats/message', message: message, user: user %>
        <% end %>
      </ul>
    </div>
    <div class="chat-message clearfix">
      <%= turbo_frame_tag 'message_form' do %>
        <%= render 'messages/form', message: Message.new, chat: chat %>
      <% end %>
    </div>
</div>

app/views/chats/_chat_placeholder.html.erb
<div class="chat " style='height: 35rem'>
    <div class="chat-history" style='height: 100%; text-align:center'>
        <span class="badge bg-light text-dark" style='margin-top: 25%'>Select a chat to start messaging</span>
    </div>
</div>

app/views/chats/_friend_item.html.erb
<%= link_to(chat_path(current_user.chat_with(friend)), data: { turbo_frame: "chat" }, class: "btn btn--primary") do%>
    <li class="clearfix">
        <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="avatar">
        <div class="about">
            <div class="name"><%= friend.username %></div>
            <div class="status"> <i class="fa fa-circle offline"></i> left 7 mins ago </div>
        </div>
    </li>
<% end %>

app/views/chats/_message.html.erb
<% is_opponent = message.user != user %>
<li class="clearfix">
    <div class="message-data <%= is_opponent ? 'text-right' : '' %>">
        <span class="message-data-time"><%= message.created_at.strftime('%m/%d/%y %I:%M%p') %></span>
        <% if is_opponent %>
          <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar">
        <% end %>
    </div>
    <div class="message <%= is_opponent ? 'other-message float-right' : 'my-message' %>"><%= message.content %></div>
</li>

app/views/chats/index.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<div class="container">
<div class="row clearfix">
    <div class="col-lg-12">
        <div class="card chat-app">
            <div id="plist" class="people-list">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-search"></i></span>
                    </div>
                    <input type="text" class="form-control" placeholder="Search...">
                </div>
                <%= turbo_frame_tag 'friends' do %>
                  <ul class="list-unstyled chat-list mt-2 mb-0">
                    <% @friends.each do |friend| %>
                      <%= render 'friend_item', friend: friend %>
                    <% end %>
                  </ul>
                <% end %>
            </div>
            <%= turbo_frame_tag "chat" do %>
              <%= render 'chat_placeholder', chat: @chat %>
            <% end %>
        </div>
    </div>
</div>
</div>
<style>
body{
    background-color: #f4f7f6;
    margin-top:20px;
}
.card {
    background: #fff;
    transition: .5s;
    border: 0;
    margin-bottom: 30px;
    border-radius: .55rem;
    position: relative;
    width: 100%;
    box-shadow: 0 1px 2px 0 rgb(0 0 0 / 10%);
}
.chat-app .people-list {
    width: 280px;
    position: absolute;
    left: 0;
    top: 0;
    padding: 20px;
    z-index: 7
}

.chat-app .chat {
    margin-left: 280px;
    border-left: 1px solid #eaeaea
}

.people-list {
    -moz-transition: .5s;
    -o-transition: .5s;
    -webkit-transition: .5s;
    transition: .5s
}

.people-list .chat-list li {
    padding: 10px 15px;
    list-style: none;
    border-radius: 3px
}

.people-list .chat-list li:hover {
    background: #efefef;
    cursor: pointer
}

.people-list .chat-list li.active {
    background: #efefef
}

.people-list .chat-list li .name {
    font-size: 15px
}

.people-list .chat-list img {
    width: 45px;
    border-radius: 50%
}

.people-list img {
    float: left;
    border-radius: 50%
}

.people-list .about {
    float: left;
    padding-left: 8px
}

.people-list .status {
    color: #999;
    font-size: 13px
}

.chat .chat-header {
    padding: 15px 20px;
    border-bottom: 2px solid #f4f7f6
}

.chat .chat-header img {
    float: left;
    border-radius: 40px;
    width: 40px
}

.chat .chat-header .chat-about {
    float: left;
    padding-left: 10px
}

.chat .chat-history {
    padding: 20px;
    border-bottom: 2px solid #fff
}

.chat .chat-history ul {
    padding: 0
}

.chat .chat-history ul li {
    list-style: none;
    margin-bottom: 30px
}

.chat .chat-history ul li:last-child {
    margin-bottom: 0px
}

.chat .chat-history .message-data {
    margin-bottom: 15px
}

.chat .chat-history .message-data img {
    border-radius: 40px;
    width: 40px
}

.chat .chat-history .message-data-time {
    color: #434651;
    padding-left: 6px
}

.chat .chat-history .message {
    color: #444;
    padding: 18px 20px;
    line-height: 26px;
    font-size: 16px;
    border-radius: 7px;
    display: inline-block;
    position: relative
}

.chat .chat-history .message:after {
    bottom: 100%;
    left: 7%;
    border: solid transparent;
    content: " ";
    height: 0;
    width: 0;
    position: absolute;
    pointer-events: none;
    border-bottom-color: #fff;
    border-width: 10px;
    margin-left: -10px
}

.chat .chat-history .my-message {
    background: #efefef
}

.chat .chat-history .my-message:after {
    bottom: 100%;
    left: 30px;
    border: solid transparent;
    content: " ";
    height: 0;
    width: 0;
    position: absolute;
    pointer-events: none;
    border-bottom-color: #efefef;
    border-width: 10px;
    margin-left: -10px
}

.chat .chat-history .other-message {
    background: #e8f1f3;
    text-align: right
}

.chat .chat-history .other-message:after {
    border-bottom-color: #e8f1f3;
    left: 93%
}

.chat .chat-message {
    padding: 20px
}

.online,
.offline,
.me {
    margin-right: 2px;
    font-size: 8px;
    vertical-align: middle
}

.online {
    color: #86c541
}

.offline {
    color: #e47297
}

.me {
    color: #1d8ecd
}

.float-right {
    float: right
}

.clearfix:after {
    visibility: hidden;
    display: block;
    font-size: 0;
    content: " ";
    clear: both;
    height: 0
}

@media only screen and (max-width: 767px) {
    .chat-app .people-list {
        height: 465px;
        width: 100%;
        overflow-x: auto;
        background: #fff;
        left: -400px;
        display: none
    }
    .chat-app .people-list.open {
        left: 0
    }
    .chat-app .chat {
        margin: 0
    }
    .chat-app .chat .chat-header {
        border-radius: 0.55rem 0.55rem 0 0
    }
    .chat-app .chat-history {
        height: 300px;
        overflow-x: auto
    }
}

@media only screen and (min-width: 768px) and (max-width: 992px) {
    .chat-app .chat-list {
        height: 650px;
        overflow-x: auto
    }
    .chat-app .chat-history {
        height: 600px;
        overflow-x: auto
    }
}

@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) and (orientation: landscape) and (-webkit-min-device-pixel-ratio: 1) {
    .chat-app .chat-list {
        height: 480px;
        overflow-x: auto
    }
    .chat-app .chat-history {
        height: calc(100vh - 350px);
        overflow-x: auto
    }
}
</style>

app/views/chats/show.html.erb
<%= turbo_frame_tag "chat" do %>
  <%= render 'chat_item', chat: @chat, user: current_user %>
<% end %>

app/views/games/_game.html.erb
<div id='game_<%= game.id %>'>
  <div class="display" id='status'>
      <%= raw game.decorided_status %>
  </div>
  <div class="toe-container" data-controller='desk' data-desk-id-value="<%= game.id %>" >
      <% game.state.each_with_index do |tile, i| %>
        <div id='<%= i %>'  class="tile player<%= tile %>" data-controller='game' data-action="click->game#make_turn"><%= tile %></div>
      <% end %>
  </div>
  <div class="display announcer hide"></div>
  <div class="controls">
      <button id="reset" data-controller='game' data-action="click->game#start">Reset</button>
  </div>
</div>

app/views/games/show.html.erb
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">

<main class="background">
  <div class="controls" style='float: left'>
    <%= link_to 'Home', root_path %>
  </div>

  <div class="title">
      <h1>Tic Tac Toe</h1>
  </div>
  <div class="display">
      Your sing is <span class="display-player player<%= @game.sign_of(current_user) %>"><%= @game.sign_of(current_user) %></span>
  </div>
  <%= render 'game', game: @game, user: current_user %>
</main>

<style>
* {
    padding: 0;
    margin: 0;
    font-family: 'Itim', cursive;
}

.background {
    background-color: #12181B;
    height: 100vh;
    padding-top: 1px;
}

.title {
    color: white;
    text-align: center;
    font-size: 40px;
    margin-top: 10%;
}

.display {
    color: white;
    font-size: 25px;
    text-align: center;
    margin-top: 1em;
    margin-bottom: 1em;
}

.hide {
    display: none;
}

.toe-container {
    margin: 0 auto;
    display: grid;
    grid-template-columns: 33% 33% 33%;
    grid-template-rows: 33% 33% 33%;
    max-width: 300px;

}

.tile {
    border: 1px solid white;
    min-width: 100px;
    min-height: 100px;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 50px;
    cursor: pointer;
}

.playerX {
    color: #09C372;
}

.playerO {
    color: #498AFB;
}

.controls {
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    margin-top: 1em;
}

.controls button {
    color: white;
    padding: 8px;
    border-radius: 8px;
    border: none;
    font-size: 20px;
    margin-left: 1em;
    cursor: pointer;
}

.controls a {
    color: white;
    padding: 8px;
    border-radius: 8px;
    border: none;
    font-size: 20px;
    margin-left: 1em;
    cursor: pointer;
}

.restart {
    background-color: #498AFB;
}

#reset {
    background-color: #FF3860;
}
</style>

app/views/layouts/_appearance.html.erb
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap-extended.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/fonts/simple-line-icons/style.min.css">
<link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/colors.min.css">
<%# <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap.min.css"> %>
<link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">

<div class="appearance">
  <div class="card" style='margin-bottom: 0'>
    <div class="card-content">
      <div class="card-body">
        <div class="media d-flex">
          <div class="media-body text-left">
            <h3 id='appearance' data-controller="appearance" class="success">0</h3>
            <span>Players Online</span>
          </div>
          <div class="align-self-center">
            <i class="icon-user success font-large-2 float-right"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_top_menu.html.erb
<div class="container" style='margin-bottom: 2rem; margin-top: 2rem'>
  <header class="d-flex justify-content-center py-3">
    <ul class="nav nav-pills">
      <li class="nav-item"><a href="/" class="nav-link <%= @current_page == 'Home' ? 'active' : '' %>">Home</a></li>
      <li class="nav-item"><a href="/chats" class="nav-link <%= @current_page == 'Chats' ? 'active' : '' %>">Chats</a></li>
      <li class="nav-item"><a href="#" class="nav-link <%= @current_page == 'Add friend' ? 'active' : '' %>">Add friend</a></li>
      <li class="nav-item"><a href="#" class="nav-link <%= @current_page == 'Play offline' ? 'active' : '' %>">Play offline</a></li>
      <li class="nav-item"><a href="/clicker" class="nav-link <%= @current_page == 'Clicker' ? 'active' : '' %>">Clicker</a></li>
      <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: 'nav-link' %></li>
    </ul>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style='margin-top: 0'>
    <% if user_signed_in? && !@render_widgets %>
      <%= render 'layouts/top_menu' %>
      <%= render 'layouts/appearance' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with model: message, local: true, url: "/chats/#{chat.id}/messages/", class: 'input-group mb-0' do |f| %>
  <div class="input-group-prepend">
    <%= f.button(:submit, class: "input-group-text", data: { turbo_frame: "message_form" }) do %>
      <i class="fa fa-send"></i>
    <% end %>
  </div>
  <%= f.text_field :content, class:"form-control",  placeholder: "Enter text here..." %>
<% end %>

app/views/messages/new.html.erb
<%= turbo_frame_tag 'message_form' do %>
  <%= render 'form', message: @message, chat: @chat %>
<% end %>

app/views/pages/_friends_list.html.erb
<div class="card" style="width: 18rem;">
    <div class="card-header">
      Your Friends
    </div>
    <ul class="list-group list-group-flush">
      <% user.friends.each do |friend| %>
        <li class="list-group-item">
          <%= friend.username %>
          <%= link_to 'Create Game',
            games_path(user_id: user.id, friend_id: friend.id),
            data: { "turbo-method": :post },
            class: 'btn btn-outline-primary float-end'
          %>
        </li>
      <% end %>
    </ul>
  </div>

app/views/pages/_pending_games.html.erb
<div class="card" style="width: 18rem;">
    <div class="card-header">
      Pending Games
    </div>
    <ul class="list-group list-group-flush">
      <% user.pending_games.each do |game| %>
        <li class="list-group-item">
          <%= game.opponent_of(user).username %>
          <%= link_to 'Open', game, class: 'btn btn-outline-primary float-end' %>
        </li>
      <% end %>
    </ul>
  </div>

app/views/pages/clicker.html.erb
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700;800;900&display=swap" rel="stylesheet">
<body class='center'>
  <div class='clicker'>
    <button
      class="style-5"
      data-controller="clicker"
      data-action="click->clicker#increment"
    ><%= @count %> ⚡</button>
  </div>
</body>

app/views/pages/home.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

<div class="container">
  <div class=''>
    <h1>Welcome Home</h1>
    <div class='d-inline-block'>
      <%= render 'friends_list', user: current_user %>
    </div>
    <div class='d-inline-block'>
      <%= render 'pending_games', user: current_user %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container">
  <header class="d-flex justify-content-center py-3">
    <ul class="nav nav-pills">
      <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Features</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li>
      <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link">About</a></li>
    </ul>
  </header>
</div>
<div class='container card' style=''>
  <h1>Welcome to JoeToy</h1>
  <p>Your Chats:</p>

  <div class="list-group">
  <a href="#" class="list-group-item list-group-item-action" aria-current="true">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small>3 days ago</small>
      <span class="badge bg-primary rounded-pill" style='align: center'>1</span>
    </div>
    <p class="mb-1">Some placeholder content in a paragraph.</p>
    <small>And some small print.</small>
  </a>
  <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Some placeholder content in a paragraph.</p>
    <small class="text-muted">And some muted small print.</small>
  </a>
  <a href="#" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">List group item heading</h5>
      <small class="text-muted">3 days ago</small>
    </div>
    <p class="mb-1">Some placeholder content in a paragraph.</p>
    <small class="text-muted">And some muted small print.</small>
  </a>
</div>
</div>
<!-- app/views/pages/index.html.erb -->